
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocINleft+-left*/rightUMINUSrightUPLUSright^DEL EXP FLOAT IN LOG SI STRING VARIABLESstart : statementstart : DEL STRING\n             | VARIABLESstatement : STRING "=" expressionstatement : expressionexpression : expression \'+\' expression\n                  | expression \'-\' expression\n                  | expression \'*\' expression\n                  | expression \'/\' expression\n                  | expression \'^\' expression\n                  | expression IN expression \n                  | expression IN SIexpression : \'-\' expression %prec UMINUSexpression : \'+\' expression %prec UPLUSexpression : \'(\' expression \')\'expression : FLOATexpression : STRINGexpression : LOG \'(\' expression \')\' \n                  | EXP \'(\' expression \')\'\n    '
    
_lr_action_items = {'DEL':([0,],[3,]),'VARIABLES':([0,],[5,]),'STRING':([0,3,7,8,9,14,15,16,17,18,19,20,25,26,],[4,13,22,22,22,22,22,22,22,22,22,22,22,22,]),'-':([0,4,6,7,8,9,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[8,-17,16,8,8,8,-16,8,8,8,8,8,8,8,-14,-17,-13,16,8,8,16,-6,-7,-8,-9,-10,16,-12,-15,16,16,-18,-19,]),'+':([0,4,6,7,8,9,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[7,-17,15,7,7,7,-16,7,7,7,7,7,7,7,-14,-17,-13,15,7,7,15,-6,-7,-8,-9,-10,15,-12,-15,15,15,-18,-19,]),'(':([0,7,8,9,11,12,14,15,16,17,18,19,20,25,26,],[9,9,9,9,25,26,9,9,9,9,9,9,9,9,9,]),'FLOAT':([0,7,8,9,14,15,16,17,18,19,20,25,26,],[10,10,10,10,10,10,10,10,10,10,10,10,10,]),'LOG':([0,7,8,9,14,15,16,17,18,19,20,25,26,],[11,11,11,11,11,11,11,11,11,11,11,11,11,]),'EXP':([0,7,8,9,14,15,16,17,18,19,20,25,26,],[12,12,12,12,12,12,12,12,12,12,12,12,12,]),'$end':([1,2,4,5,6,10,13,21,22,23,27,28,29,30,31,32,33,34,35,38,39,],[0,-1,-17,-3,-5,-16,-2,-14,-17,-13,-4,-6,-7,-8,-9,-10,-11,-12,-15,-18,-19,]),'=':([4,],[14,]),'*':([4,6,10,21,22,23,24,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-17,17,-16,-14,-17,-13,17,17,17,17,-8,-9,-10,17,-12,-15,17,17,-18,-19,]),'/':([4,6,10,21,22,23,24,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-17,18,-16,-14,-17,-13,18,18,18,18,-8,-9,-10,18,-12,-15,18,18,-18,-19,]),'^':([4,6,10,21,22,23,24,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-17,19,-16,19,-17,19,19,19,19,19,19,19,19,19,-12,-15,19,19,-18,-19,]),'IN':([4,6,10,21,22,23,24,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-17,20,-16,-14,-17,-13,20,20,-6,-7,-8,-9,-10,20,-12,-15,20,20,-18,-19,]),')':([10,21,22,23,24,28,29,30,31,32,33,34,35,36,37,38,39,],[-16,-14,-17,-13,35,-6,-7,-8,-9,-10,-11,-12,-15,38,39,-18,-19,]),'SI':([20,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'statement':([0,],[2,]),'expression':([0,7,8,9,14,15,16,17,18,19,20,25,26,],[6,21,23,24,27,28,29,30,31,32,33,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> statement','start',1,'p_start_statement','calc.py',74),
  ('start -> DEL STRING','start',2,'p_start_command','calc.py',79),
  ('start -> VARIABLES','start',1,'p_start_command','calc.py',80),
  ('statement -> STRING = expression','statement',3,'p_statement_assign','calc.py',89),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',96),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calc.py',102),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calc.py',103),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calc.py',104),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calc.py',105),
  ('expression -> expression ^ expression','expression',3,'p_expression_binop','calc.py',106),
  ('expression -> expression IN expression','expression',3,'p_expression_binop','calc.py',107),
  ('expression -> expression IN SI','expression',3,'p_expression_binop','calc.py',108),
  ('expression -> - expression','expression',2,'p_expression_uminus','calc.py',138),
  ('expression -> + expression','expression',2,'p_expression_uplus','calc.py',143),
  ('expression -> ( expression )','expression',3,'p_expression_group','calc.py',148),
  ('expression -> FLOAT','expression',1,'p_expression_number','calc.py',153),
  ('expression -> STRING','expression',1,'p_expression_name','calc.py',165),
  ('expression -> LOG ( expression )','expression',4,'p_expression_func','calc.py',183),
  ('expression -> EXP ( expression )','expression',4,'p_expression_func','calc.py',184),
]
